server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
    max-threads: 1000
    min-spare-threads: 30
  servlet:
    context-path: /zh-boot-dubbo

spring:
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: net.zhenghao.zh.consumer.entity

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql