server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
    max-threads: 1000
    min-spare-threads: 30
#  servlet:
#    context-path: /zh-boot-dubbo


## Dubbo 服务消费者配置
dubbo:
  application:
    id: zh-dubbo-consumer
    name: zh-dubbo-consumer
  protocol:
    id: dubbo
    name: dubbo
    port: 20880